pr_summaries.py
release.py
update_news.py

Fixes #1
There are still some TODOs in this script:

Add release helper script

---

node_reservation.sh

This commit introduces a bash script that once sourced gives access to 6
helper functions.
node_reserve
Reserves a compute unit
Downloads the sources from github
Compile and installs the sources, at the end you have osbuild-composer
running and able to build images
node_uploadiff
from a local github repo that is shared with the instance, make a patch and
apply it on the remote instance.
node_open_tmux: opens a new tmux after the installation
node_attach_tmux: attach to a tmux instance
node_print_reservation_infos: print the IDs to export them on an other terminal
node_terminate_node: terminate the reservation for current IDs
TODO: would this be better as a python script ?

RemoteWork: Helper functions to deploy a node

---

requirements.txt

To allow for a simple `pip install -r requirements.txt` before running `release.py`

release-helper: Add requirements.txt

---

release.py

This allows for re-executing the script when already being on the
release branch and wanting to just create the pull request.

release-helper: Add base branch as optional argument

---

release.py

To make it easier for users of this script to see what values it is
executed with we now print out the config before step 1.

release-helper: Print release config

---

release.py

Also add a warning when not using this with osbuild or osbuild-composer.

release-helper: Fix crash when there are no tags

---

release.py

Currently this step fails if you don't have a pgp key.

release-helper: Fix tagging

---

release.py

Now the remote is not being guessed at all costs, which is probably the better thing to do anyway if there are >2 (upstream, fork).
Also the warning message is hopefully clearer/more helpful.

Better remote handling

---

release.py

Reference:
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

release-helper: Skip CI for release PRs

---

release.py

Previously we only relied on the latest annotated tags for getting the
latest version. If the repository contains a lightweight tag as its
latest version it would not be detected correctly.
(Alternative fix: Never push lightweight tags)

release-helper: Also discover lightweight tags

---

release.py

Fixes #25
I tested this with a dummy repository in the python interactive shell (octocat/Hello-World).

release-helper: Print responses from GH api calls

---

release.py

This commit fixes the version bumping for osbuild (regression of #34). It also drops a few overly cautionary questions.
1. We will always want to bump the version (plus on re-executing the script, the step is non-destructive)
2. We don't want to ask twice whether to update NEWS

release-helper: Fix version bumping for osbuild

---

release.py

Read the NEWS.md file (after it has been generated and amended) and push
its content to the GitHub release.
Fixes #37

release-helper: Populate GitHub release with NEWS

---

release.py

Otherwise, the script dies with the following exception:
Step: Make the notes in NEWS.md release ready using None [y/s/N] y
Traceback (most recent call last):
File "/home/obudai/work/maintainer-tools/release.py", line 493, in <module>
main()
File "/home/obudai/work/maintainer-tools/release.py", line 489, in main
release_playbook(args, repo, api)
File "/home/obudai/work/maintainer-tools/release.py", line 385, in release_playbook
subprocess.call([f'{args.editor}', 'NEWS.md'])
File "/usr/lib64/python3.9/subprocess.py", line 349, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib64/python3.9/subprocess.py", line 951, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib64/python3.9/subprocess.py", line 1821, in _execute_child
raise …

release.py: skip the editing NEWS.md step if no editor is defined

---

release.py
requirements.txt

As we have a bot on gitlab.cee that handles the Fedora Koji/Bodhi steps now we can drop these parts from the release script.

Drop fedora support

---

update-distgit.py

Pulling in the script from https://github.com/osbuild/osbuild-composer/blob/main/tools/update-distgit.py and generalize it so that it works with osbuild too.
It decides which project to build based on the folder name it is executed from.

Add update-distgit script

---

release.py

Dropping this line was an oversight in eb7eac98822293ef6f803740f3d78d4a7df18956

release-helper: Bring back pushing the tag

---

release.py

Remove the steps options from being shown when the --help flag is set.

release: remove step options

---

release.py

Lists without blank lines between items look nicer.
See for example osbuild release [37](https://github.com/osbuild/osbuild/releases/tag/v37) vs [43](https://github.com/osbuild/osbuild/releases/tag/v43).

release: don't leave empty line between changelog items

---

release.py

Without supplying a token we will run into issues with API call rate
limiting. Alternatively we could of course wait a long time between each
call, but then again it is really easy to create and supply a token.

Make the GitHub token mandatory

---

release.py

If there is no origin remote pointing to the upstream repository the release script will now warn the user. This prevents the tags from being pushed to the wrong remote.

release: check if the origin is valid

---

release.py

Cockpit-composer needs to create a tag with only the release version and no v. Otherwise the tarball and specfile will include a v since our specfile and tarball are generated by cockpit's release bot cockpituous which expects just a number in the release tag.

release: drop v in cockpit-composer tag

---

release.py

I have added two modes, specifically to make it easier to develop a release bot based no this script.
The `--no-interactive` option is a little dangerous as it also pushes the tag to the upstream repository.
The `--dry-run` option does what it says on the packaging. It can be used in combination with `--no-interactive`.

Non interactive tagging and dry run

---

runner-cleanup.sh

Script that removes any old CI runners that failed to be terminated
for any reason.

runner-cleanup: Add script for manual CI runner cleanup

---

LICENSE

There was missing license file in the repository. As this is part of osbuild
project I have copy paste license we use in other repos.

License: Add missing license file to the project
